"""Model3

Revision ID: 9aa73e043b68
Revises: ecefd114cbf7
Create Date: 2025-01-22 23:47:34.680390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aa73e043b68'
down_revision: Union[str, None] = 'ecefd114cbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscriptions_artikul', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.alter_column('products', 'artikul',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_products_id', table_name='products')
    op.drop_index('ix_products_artikul', table_name='products')
    op.create_index(op.f('ix_products_artikul'), 'products', ['artikul'], unique=False)
    op.drop_column('products', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_products_artikul'), table_name='products')
    op.create_index('ix_products_artikul', 'products', ['artikul'], unique=True)
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.alter_column('products', 'artikul',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('subscriptions',
    sa.Column('artikul', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('next_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('artikul', name='subscriptions_pkey')
    )
    op.create_index('ix_subscriptions_artikul', 'subscriptions', ['artikul'], unique=False)
    # ### end Alembic commands ###
