"""Model2

Revision ID: ecefd114cbf7
Revises: de8aa26557aa
Create Date: 2025-01-22 22:10:27.945512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecefd114cbf7'
down_revision: Union[str, None] = 'de8aa26557aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('artikul', sa.String(), nullable=False),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('artikul')
    )
    op.create_index(op.f('ix_subscriptions_artikul'), 'subscriptions', ['artikul'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_artikul'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
